// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddvrucciglfqwwueabdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkdnJ1Y2NpZ2xmcXd3dWVhYmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODAzMzcsImV4cCI6MjA3MjQ1NjMzN30.yQegyzJRnmE-3TQ9FdHfe0ZH_04BnuoDBRGXWQJV7UY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});